- scripts/apply_release.sh
- scripts/create_base_env.sh
When you install `conda-wrappers` it makes a wrappered version of your bin. You want to do this last so that all of your scripts prior to the install get wrappered, as this wrapped bin is useful for launching apps.
> FIX: install conda-wrappers last

- scripts/apply_release.sh
We're going to have a long road of tweaking these releases. I plan to leave all the dud tags but erase all the dud environments in our installs.
> FIX: conda install with -y flag to skip y/n prompt

- pcds.yaml
Pick up the newest tags of our modules.
The diff here isn't really interpretable because we've taken out the exact build specification in a previous PR.
> ENH: updated pcds to 0.6.0

- pcds.yaml
- scripts/packages.txt
Updated pydm for bugfixes, fulfil package requests. There shouldn't be any API breaks, but we may have gained features.
- `pydm` -> 1.2.0 for bugfixes
- add `h5py`
- add `coverage`
- misc version bumps from conda
closes #43 
closes #45
> pcds-1.1.1

- pcds.yaml
- Add `python-graphviz`, the magical extra package you need to install on top of graphviz to actually use it in python.
> ENH: updated pcds to 1.2.3

- pcds.yaml
Pick up `timechart=1.1.0`, and other misc
> ENH: updated pcds to 2.0.1

- .travis.yml
These builds exploded because of a subtle issue with how we set it up. We were doing the following:
1. install conda
2. activate conda
3. update conda
4. create test-environment
5. activate test-environment
Unfortunately, the updated version of conda and the original version of conda had different conventions about how we change the path to pick up the conda binary. The old `conda activate` (to get into the base env) and the new `conda activate test-environment` were incompatible, so we ended up without conda on the path immediately after the second command, causing the build to fail.
The solution is simple: always reboot conda after updating it.
@teddyrendahl the build still fails due to an issue in the `happi` tests. They appear to be designed to skip the `mongomock` tests when it is …
> CI: reboot conda after updating conda to avoid subtle path bugs

- pcds.yaml
Notable Intended Changes:
- `pytmc` update from `2.3.1` to `2.4.0`
Notable Unintended Changes:
- `ipython` from `7.9.0` to `7.10.1`
- `jupyter_console` regression from `6.0.0` to `5.2.0`
> ENH: updated pcds to 2.3.4

- test_setup.py
Otherwise, we may miss submodules needed to run tests
> TST: check out tests recursively

- scripts/apply_release.sh
This package was super useful in the past because `source activate` is slow, and it would let you run a script in your environment without needing to `source activate`. `conda activate` is fast, so downside of having an extra package installed after the main install outweighs any upside here.
Note: conda-wrappers needed to be installed last so it could wrap all scripts provided by every previously installed package.
> API: stop using conda-wrappers

- test_setup.py
Builds were failing because pcdshub/epics-pypdb does not have a versioneer version prefix defined. I'm going to assume that a missing configuration here means no prefix, and if this is not true for a future repo we'll take care of it then.
> CI: assume no prefix if not specified

- envs/pcds/env.yaml
Requested by @ZryletTC to get vacuum devices into live environment
Only other intended change was a bugfix on pcdsdaq to make it work for the det and tst daqs
This should also fix the broken travis on the "Latest Env" build (the only build that really should never fail, unless something bad happens to a specific package build)
> ENH: updated pcds to 3.0.1

- scripts/run_all_tests.sh
The `pyca` tests are timing out sometimes. I think that test suite takes randomly between 4 and 6 minutes or so to run on travis. Here I increase the timeout length from 5m to 10m. This should be OK (not overrun the travis timeout) because packages will not timeout often and we do not retry any package that has timed out.
> MNT: increase timeout length

- scripts/check_master_tags.py
Add script to do a survey of our repos for needed tags. This will help us identify which repos need to be tagged prior to making a deployed conda environment.
It works by doing a `git clone --depth 1`, then seeing if `git describe --tags` finds anything. If `master` has a tag in this shallow clone, we will we see it here, otherwise we will get an error. This means that master is untagged.
This script is messy in places, but it gets the job done.
Sample output:
```
(top section repeated n times for n repo clones so you know it's working)
Cloning into 'check_tag_tmp'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 117 (delta 7), reused 37 (delta 2), pack-reused 0
Receiving objects: …
```
> ENH: add script to check if master needs a tag

- deploy/crontab_line.txt
- typo in my crontab
- some authentication problem that I need to resolve WIP
```
Deploying conda env to all operator machines.
Deploying on cxi-control
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Deploying on cxi-daq
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Deploying on mec-control
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Deploying on mec-daq
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```
> ENH: crontab fix

- envs/pcds/conda-packages.txt
This is required to move up to py38, and it's bad practice to let regressive pins sit in the environment.
Let's see what happens!
Which repos' tests fail? All of them? None of them? A select few?
closes #139
> MNT: remove pytest pin

- scripts/stage_release.sh
Long-standing bug that I kept forgetting to document/fix
These files can be edited while staging a new release, but they were not among the files automatically added to the commit
> MNT: make stage_release commit the updated tags

- envs/pcds/extra-tests.sh
Random idea I had while thinking about #172
Failure echo is like:
Did not find pcdswidgets in PYQTDESIGNERPATH=/cds/home/z/zlentz/miniconda3/envs/dev/etc/typhos:/cds/home/z/zlentz/miniconda3/envs/dev/etc/pydm:
> TST: add basic designer inclusion check

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
Hold pyqtgraph back to `0.11.1` to avoid an incompatibility with pydm. Thank you for the warning @hhslepicka
> Release pcds-4.1.1 (bugfix)

- deploy/hosts.txt
Noticed this was broken on mfx-console last week. Would also be good to have on the other CXI machines.
> MNT: Add missing hosts in MFX and CXI

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
- envs/pcds/pip-packages.txt
- scripts/release_notes_table.py
Auto-generated environment diff:
Added the Following Dependencies
--------------------------------
- alembic (required by tiled)
- argon2-cffi-bindings (required by argon2-cffi, which is used in bluesky, bluesky-live, ipython, jupyter, tiled, xarray)
- asttokens (required by stack-data, stack_data, which are used in ipython)
- executing (required by stack-data, stack_data, which are used in ipython)
- flit-core (required by argon2-cffi, which is used in bluesky, bluesky-live, ipython, jupyter, tiled, xarray)
- libimagequant (required by pillow, which is used in bluesky-live, hutch-python, ipython, ophyd, scikit-image, scikit-learn, suitcase-tiff, tiled, xarray)
- libllvm13 (required by libclang)
- libnsl (required by python)
- mako (required by alembic, which is used in tiled)
- pure_eval …
> ENH: updated pcds to 5.2.0

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
Goal: pick up pydm tag, hope that nothing breaks
SLAC Package Updates
--------------------
| Package |  Old   |  New   |                    Release Notes                     |
|:-------:|:------:|:------:|:----------------------------------------------------:|
|   pydm  | 1.12.0 | 1.13.0 | https://github.com/slaclab/pydm/releases/tag/v1.13.0 |
Other Python Community Major Updates
------------------------------------
|       Package        |  Old   |  New  |
|:--------------------:|:------:|:-----:|
|       humanize       | 3.14.0 | 4.0.0 |
|    python-slugify    | 5.0.2  | 6.0.1 |
| cyclonedx-python-lib | 0.12.3 | 1.3.0 |
|         lz4          | 3.1.10 | 4.0.0 |
|      pip-audit       | 1.1.2  | 2.0.0 |
> ENH: updated pcds to 5.2.2

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
Not 100% sure I'm going to push this through as-is, but I need some sort of modern environment with bluesky-queueserver for UED (and, maybe for other endstations later?)
Added the queueserver, removed the pin on pyqtgraph, added a pin for markupsafe's API break
Added the Following Packages
----------------------------
- bluesky-queueserver
Added the Following Dependencies
--------------------------------
- aioredis (required by bluesky-queueserver)
- bluesky-kafka (required by bluesky-queueserver)
- json-rpc (required by bluesky-queueserver)
- libgcrypt (required by libgsasl)
- libgpg-error (required by libgcrypt)
- libgsasl (required by librdkafka)
- librdkafka (required by python-confluent-kafka)
- python-confluent-kafka (required by bluesky-kafka)
Packages With Degraded Versions …
> ENH: pcds-5.3.0

- deploy/deploy_all
- deploy/validate_unpack
- deploy/validate_unpack_all
- envs/pcds/env.yaml
Adds deployment scripts to verify that everything went smoothly.
`validate_unpack` will tell you if your specific unpacked directory looks OK.
`validate_unpack_all` will check all of the servers using the previous script.
The operating principle is:
1. Check if the directory is where it should be
2. Check if there are still placeholder_placeholder texts sitting around
> ENH: Validate unpack

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
- envs/pcds/extra-tests.sh
- scripts/check_py_compat.sh
- Small feature/bugfix/maint update
- Script for checking ability to update to next python version
PCDS Package Updates
--------------------
|   Package   |  Old  |  New  |                       Release Notes                        |
|:-----------:|:-----:|:-----:|:----------------------------------------------------------:|
| pcdsdevices | 7.0.1 | 7.1.0 | https://github.com/pcdshub/pcdsdevices/releases/tag/v7.1.0 |
|    typhos   | 2.3.3 | 2.4.0 |   https://github.com/pcdshub/typhos/releases/tag/v2.4.0    |
- Fix a packaging issue with `pcdswidgets` and `typhos` that gave confusing error messages on opening `designer`.
SLAC Package Updates
--------------------
| Package |  Old   |  New   |                    Release Notes                     | …
> ENH: pcds-5.5.1

- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
- envs/pcds/extra-install-steps.sh
- envs/pcds/pip-packages.txt
Goals:
- pydm update
- databroker back to release instead of pre-release
- some stuff I slipped in for pmpsdb_client
- incidental python 3.10 test suite compatibility
Note that if there are any packages that were added for databroker v2, they are still lingering. They wouldn't be removed until a major release, because we are building the envs incrementally from the previous env instead of from scratch.
The diff is slightly misleading since we really want the diff since pcds-5.5.1, I'll grab the script release notes output:
PCDS Package Updates
--------------------
|  Package  |  Old   |  New   |                       Release Notes                       |
|:---------:|:------:|:------:|:---------------------------------------------------------:|
|   hxrsnd  | 0.2.9  | 0.2.11 | …
> ENH: pcds-5.6.0

- .github/workflows/integration_test.yaml
This is a v0 of getting github actions rolling with this repo. I learned the basics today.
This PR is mostly just to activate github actions on this repo.
So far, this just checks if the most recent environment can be built and runs the tests (it currently cannot be built)
Any thoughts on implementation details? I'm thinking I might drop the libmamba solver and revert back to just using `mamba` since I've had some strange warning/error output messages. I also think I should refactor a bit into some re-usable actions.
I think ultimately I want it to be structured something like:
- Job to set up miniconda/mamba artifact (not using micromamba since our main envs don't use it)
- Pass artifact to build matrix to check build compatibility and give conda pack output artifacts. Try yaml as-is, …
> CI: basic github actions

- .github/actions/release_notes/action.yml
- .github/workflows/integration_test.yaml
- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
- envs/pcds/keep-updated.txt
- envs/pcds/pip-packages.txt
- scripts/release_notes_table.py
- scripts/stage_release.sh
- Fix a bug in `stage_release.sh` (and accompanying `shellcheck`)
- Build the new environment
- Make many of the builds clone with greater depth, some of scripts compare against `master` branch which is not present with the default shallow clone
This PR is complete once the current-env-tests pass on gha and locally, once the packages look good and look like they definitely close all these PRs, and when the gha automatically produces a correct release notes blob that I can include in this description.
closes https://github.com/pcdshub/pcds-envs/issues/227
closes https://github.com/pcdshub/pcds-envs/issues/266
closes https://github.com/pcdshub/pcds-envs/issues/267
closes https://github.com/pcdshub/pcds-envs/issues/270
closes https://github.com/pcdshub/pcds-envs/issues/271
closes …
> REL: pcds-5.7.0

- .github/workflows/integration_test.yaml
- .gitignore
- envs/pcds/conda-packages.txt
- envs/pcds/env.yaml
- envs/pcds/keep-updated.txt
- envs/pcds/pip-packages.txt
- scripts/create_incremental_env.sh
- scripts/release_notes_table.py
- scripts/update_tags.py
Update the env to fix issues found in week 1 and include small pcdsdevices updates.
PR stays as draft until I get CI to pass and an automatic docs table
Other changes from top to bottom in the diff:
- Update tags in the CI when appropriate to fix an issue where some of the other builds would always recreate the current env in the weekly build
- Export the environment at the end of the incr and next env steps in case I want to nab that file after the weekly build and use it as the next release
- Add a new temp file to gitignore
- Update specs to fix issues
- close #271 again
- close #281 
- Pin packaging<22 and justify via the removal of `LegacyVersion` (this is required for the pip build to not roll over the constraint here, since some newer packages want newer packaging)
- Fix an issue …
> REL: pcds-5.7.1

- .github/actions/release_notes/action.yml
I previously noticed that:
- the release notes builder would show "no change" except when I was trying to update for a tag
- the release notes were identical between all the passing builds
The reason for this is that the release notes table builder works by looking at the diff between the old and the new env.yaml file. Since I was only updating the env.yaml file in the event of a new tag, this is the only time the release notes script had reasonable output. This also explains why each build has the same notes: they all were running off the same build-independent file.
In this fix I just add an env export to the release notes action, to make sure that it is always done before it is needed.
If the various builds have differing release notes generated by the gha here (e.g. current env shows …
> FIX: update env spec for ci release notes table

- envs/pcds/conda-packages.txt
- scripts/release_notes_table.py
- add `atef` to the release notes table
- remove `epicscorelibs`'s specific pin, we can trust the conda forge build dependencies now
> MAINT: atef in release table, unpin epicscorelibs

- .gitignore
- envs/pcds/conda-security.txt
- scripts/create_base_env.sh
- scripts/create_incremental_env.sh
- scripts/pip_audit_markdown.py
- Add a place to put security-based/CVE response pins and populate it
- Ignore the incorrect mkdocs CVE
I think I'd rather do this as we go instead of all at once at env tag time
> MAINT: make sure the next env covers new CVEs

- envs/pcds/conda-security.txt
CVE-2023-49083 was revealed in the weekly build
I made this using only the github interface so it hasn't been tested yet, but I think this is essentially an auto-merge if the "next incr" build passes.
> MAINT: update cryptography for CVE

- envs/pcds/conda-security.txt
I think the old pins can be dropped once the base environment has them included.
This commit will make our next env avoid the following:
CVE-2024-22190
CVE-2024-22195
> SEC: clear old security pins, add new ones

- scripts/apply_release.sh
I commented these out as part of a debug process and never brought them back
These lines ensure that your local repo is up to date and switches to the correct tag before creating a deployed release.
They don't do anything if you are trying to apply the latest, so my deployment is unaffected.
> FIX: reinstate git actions in apply script

- envs/pcds/keep-updated.txt
- envs/pcds/pip-packages.txt
- scripts/release_notes_table.py
We don't depend on ophyd-async (yet?), and it was the cause of some amount of build conflicts.  
Instead I advocate we remove it and have people venv it if they want
> BLD: remove ophyd async

- scripts/check_master_tags_ghapi.py
I ran this and thought there was probably a better way than cloning each repo and checking what tag got pulled
Uses ghapi, and apparently doesn't even need a PAT to work (running as unauthenticated will show a warning but progress just fine)
> ENH: check tags with ghapi to avoid cloning all repos

- scripts/update_tags.py
Closes #351 
Simply changes the url used to get package tag information.  The old one seems to have died.
Tested by running this function on `slac-alarm-manager` (the failing case) and `happi` (the case I trusted to be working)
```python
In [1]: from scripts.update_tags import pypi_latest_version_no_search
In [2]: pypi_latest_version_no_search("happi")
Out[2]: '2.6.0'
In [3]: pypi_latest_version_no_search("slac-alarm-manager")
Out[3]: '1.3.0'
```
> BUG: update url used to grab tag information

- envs/pcds/conda-packages.txt
- envs/pcds/pip-packages.txt
- scripts/create_base_env.sh
- scripts/get_extras.py
Apparently line-profiler hasn't strictly required ipython for a while, and at least locally it seems like I can install 4.1.2 while pinning ipython at 8.4.0.  
Curiosity getting me here since I don't want to do other more "productive" things
> BLD: line profiler no longer requires ipython, unpin needed for py3.12

- .github/workflows/integration_test.yaml
See title, this is the other place we have jobs that run on the deprecated ubuntu runners.
I'll have to rebase the 3.12 env build pr on this to get the jobs to run
> BLD: update all runners to ubuntu-latest

- .github/workflows/integration_test.yaml
- envs/pcds/a_pcds-envs_deactivate.sh
- envs/pcds/extra-install-steps.sh
- envs/pcds/z_pcds-envs_activate.sh
- Removes py3.12 readiness check, we're on py3.12 now
- Set QT_XCB_INTEGRATION environment variable as part of conda environment activation
- selects qt designer plugin based on python version
> Mnt 6.0.0 fixups

- envs/pcds/env.yaml
blop pulled in an old version of `ortools`, which pinned `protobuf` back to a version that didn’t work with `grpcio_tools`
It's possible to update ortools and bring protobuf along with it, blop doesn't actually pin `ortools`.  I'm not sure why this originally grabbed an older version.
I'll check to see if the fresh install has this same issue.  We're looking for:
protobuf=5.29
grpcio_tools=1.71
ortools=9.12
> BLD: update ortools and protobuf to match grpcio-tools.
