pcdshub/pcds-envs

pcds.yaml

- ``hutch-python 0.2.1``
- incidental latest

ENH: updated pcds to 0.6.1

---

pcds.yaml
scripts/create_base_env.sh
scripts/packages.txt

- Add `typhon`
- Pin `tornado<5.0.0`
- `ophyd=1.2.0`, with fixed tests in our packages
- `qdarkstyle` from `conda`
- Add `anaconda-client`
closes #33 
closes #47 
closes #48 
closes #49 
closes #50

REL: pcds-1.2.0

---

pcds.yaml
scripts/packages.txt

ENH: Rel 1.2.2

---

pcds.yaml

- `psdm_qs_cli` keeps updating and Silke needs it
- Incidentally pick up `pydm` bugfix

ENH: updated pcds to 1.2.5

---

envs/pcds/conda-packages.txt
envs/pcds/env.yaml
envs/pcds/extra_tests.sh

MNT: move to the new and improved typhos

---

scripts/test_setup.py

closes #113 
Reveals that the build is broken

MNT: add conda-forge to checked channels

---

envs/pcds/conda-packages.txt

closes #120 
Should work on psbuild based on Ken's investigation he logged in that issue

ENH: Add pre-commit to pcds environment

---

envs/pcds/conda-packages.txt

conda-pack is useful and is getting use in this repo now
conda-smithy is relevant now that we're starting to work with conda-forge

ENH: add conda-pack and conda-smithy

---

envs/pcds/conda-packages.txt

Hopefully this makes the travis cron happy again

MNT: hold back package to avoid new bug

---

envs/pcds/conda-packages.txt
envs/pcds/env.yaml
envs/pcds/keep-updated.txt
envs/pcds/package-tests.txt

ENH: pcds-3.3.3

---

envs/pcds/conda-packages.txt
envs/pcds/keep-updated.txt

- closes #174 
- Also sets databroker as a "keep-updated" package

MNT: Add bluesky-live

---

scripts/run_all_tests.sh

I think we expect this to fail for the current environment
closes #176

TST: add pip check to tests

---

envs/pcds/conda-packages.txt

ENH: add python-ldap

---

envs/pcds/conda-packages.txt
envs/pcds/env.yaml

Notable updates to pcdsdevices and hutch-python
Hopefully when I sign on tomorrow it's just passing and green

ENH: updated pcds to 4.1.2

---

deploy/hosts.txt
envs/pcds/conda-packages.txt
envs/pcds/env.yaml
envs/pcds/keep-updated.txt

PCDS package updates:
|  Package | Old | New |
| - | - | - |
| elog | 1.0.2 | 1.2.0 |
| nabs | 1.1.1 | 1.1.2 |
| pcdscalc | 0.2.0 | 0.3.0 |
| pytmc | 2.9.0 | 2.9.1 |
Lab community package notable updates:
N/A, misc minor releases
Python community package notable updates:
N/A, misc minor releases

ENH: updated pcds to 4.1.3

---

envs/pcds/conda-packages.txt
envs/pcds/env.yaml

Pin scikit-image to avoid config loading bug

pcds-4.1.4

---

envs/pcds/a_pcds-envs_deactivate.sh
envs/pcds/z_pcds-envs_activate.sh
scripts/apply_release.sh
scripts/create_base_env.sh
scripts/install_activate.sh

Not quite done, needs shellcheck and testing still
Goal: have a mechanism for including activate/deactivate scripts per env
Added scripts for our env that just set up the site-specific EPICS config as a workaround for epics-base packaging conflicts with the site-specific EPICS packaging.

ENH: environment activate scripts, epics setup

---

.travis.yml
deploy/hosts.txt
envs/pcds/conda-packages.txt
envs/pcds/env.yaml
scripts/run_all_tests.sh

These won't become a new env yet but I want to do them while they're on my mind.
- unpin scikit-image because it is blocking py310. Regardless of pinning, this won't be updated in live envs until the python update.
- closes #257 
- re-order the deploy hosts lists to hit the host that asks me for password auth first, so I can do that and then walk away to work on other things
- retry on timeouts for more clear results

MAINT: post pcds-5.5.1 tweaks

---

envs/pcds/conda-packages.txt
envs/pcds/env.yaml
envs/pcds/keep-updated.txt

forcing v2 pre-release is breaking things
closes #260

MAINT: use latest release of databroker as the default

---

envs/pcds/conda-security.txt

Another CVE revealed in the latest weekly build, let's make it not happen for the next env

MAINT: include aiohttp cve patch

---

envs/pcds/conda-security.txt

[CVE-2023-49080](https://github.com/advisories/GHSA-h56g-gq9v-vc8r)

MAINT: minor CVE
